[package]
name = "ptoxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.0"
logos = "0.13.0"
pest = "2.7.5"
pest_derive = "2.7.5"
thiserror = "1.0.50"
